#!/bin/bash
# Copyright (c) 2023 Michael Neill Hartman. All rights reserved.

cd /server
cabal run
# this file is the entrypoint for the docker image
# which runs the server executable when the container is started
