#!/bin/bash

# Copyright (c) 2023 Michael Neill Hartman. All rights reserved.
# mnh_license@proton.me
# https://github.com/hartmanm

# test_run

# with local mountpoint
# bash hs_server

# with no actual mountpoint
#bash hs_server ./no_path

# with TEST_SRC_DIRECTORY
START=`pwd`
[[ ! -d tests ]] && mkdir -p tests
TEST_SRC_DIRECTORY=`cd tests; pwd`
cd ${START}
cd ..
echo $TEST_SRC_DIRECTORY
sleep 1
bash hs_server $TEST_SRC_DIRECTORY
